const API_CONFIG = { SERVICE_KEY: 'YOUR_SERVICE_KEY_HERE', BASE_URL: 'https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getUltraSrtNcst', FORECAST_URL: 'https://apis.data.go.kr/1360000/VilageFcstInfoService_2.0/getVilageFcst', NX: 98, NY: 76 };
const elements = { currentTemp: document.getElementById('current-temp'), weatherDesc: document.getElementById('weather-desc'), rainAmount: document.getElementById('rain-amount'), popChance: document.getElementById('pop-chance'), humidity: document.getElementById('humidity'), windSpeed: document.getElementById('wind-speed'), windDirection: document.getElementById('wind-direction'), currentTime: document.getElementById('current-time'), lastUpdateTime: document.getElementById('last-update-time'), refreshBtn: document.getElementById('refresh-btn'), app: document.getElementById('app'), weatherIcon: document.getElementById('weather-icon') };
function getKMATime() { const now = new Date(); const year = now.getFullYear(); const month = String(now.getMonth() + 1).padStart(2, '0'); const date = String(now.getDate()).padStart(2, '0'); let hours = now.getHours(); let minutes = now.getMinutes(); if (minutes < 45) { hours -= 1; if (hours < 0) hours = 23; } const baseDate = `${year}${month}${date}`; const baseTime = `${String(hours).padStart(2, '0')}00`; return { baseDate, baseTime }; }
function getVilageTime() { const now = new Date(); const year = now.getFullYear(); const month = String(now.getMonth() + 1).padStart(2, '0'); const date = String(now.getDate()).padStart(2, '0'); const times = [2, 5, 8, 11, 14, 17, 20, 23]; let hour = now.getHours(); let baseHour = 2; for (let t of times) { if (hour >= t) baseHour = t; else break; } if (now.getMinutes() < 15 && hour === baseHour) { const idx = times.indexOf(baseHour); baseHour = idx > 0 ? times[idx-1] : 23; } const baseDate = `${year}${month}${date}`; const baseTime = `${String(baseHour).padStart(2, '0')}00`; return { baseDate, baseTime }; }
function getWindDirection(deg) { const directions = ['북', '북북동', '북동', '동북동', '동', '동남동', '남동', '남남동', '남', '남남서', '남서', '서남서', '서', '서북서', '북서', '북북서', '북']; const index = Math.round(deg / 22.5); return directions[index]; }
function updateUI(weatherData) { elements.currentTemp.textContent = weatherData.temp; elements.rainAmount.textContent = weatherData.rain; elements.popChance.textContent = weatherData.pop || "--"; elements.humidity.textContent = weatherData.humidity; elements.windSpeed.textContent = weatherData.windSpeed; elements.windDirection.textContent = getWindDirection(weatherData.windDir); elements.weatherDesc.textContent = weatherData.desc; elements.app.className = weatherData.bgClass; createIcon(weatherData.bgClass); const now = new Date(); elements.lastUpdateTime.textContent = `${String(now.getHours()).padStart(2, '0')}:${String(now.getMinutes()).padStart(2, '0')}`; }
async function fetchWeather() { const { baseDate, baseTime } = getKMATime(); try { if (API_CONFIG.SERVICE_KEY === 'YOUR_SERVICE_KEY_HERE') throw new Error('API Key Missing'); const url = `${API_CONFIG.BASE_URL}?serviceKey=${API_CONFIG.SERVICE_KEY}&numOfRows=10&pageNo=1&dataType=JSON&base_date=${baseDate}&base_time=${baseTime}&nx=${API_CONFIG.NX}&ny=${API_CONFIG.NY}`; const response = await fetch(url); const data = await response.json(); if (data.response.header.resultCode !== '00') throw new Error(data.response.header.resultMsg); const items = data.response.body.items.item; const parsed = {}; items.forEach(item => { parsed[item.category] = item.obsrValue; }); const weatherState = { temp: parsed.T1H, rain: parsed.RN1, humidity: parsed.REH, windSpeed: parsed.WSD, windDir: parsed.VEC, desc: getDescFromPTY(parsed.PTY, parsed.T1H), bgClass: getBgClassFromPTY(parsed.PTY), pop: await fetchPOP() }; updateUI(weatherState); } catch (error) { showSampleData(); } }
async function fetchPOP() { try { const { baseDate, baseTime } = getVilageTime(); const url = `${API_CONFIG.FORECAST_URL}?serviceKey=${API_CONFIG.SERVICE_KEY}&numOfRows=50&pageNo=1&dataType=JSON&base_date=${baseDate}&base_time=${baseTime}&nx=${API_CONFIG.NX}&ny=${API_CONFIG.NY}`; const response = await fetch(url); const data = await response.json(); const items = data.response.body.items.item; const popItem = items.find(item => item.category === 'POP'); return popItem ? popItem.fcstValue : "--"; } catch (e) { return "0"; } }
function getDescFromPTY(pty, temp) { if (pty == 0) return "맑음"; if (pty == 1) return "비"; if (pty == 2) return "진눈깨비"; if (pty == 3) return "눈"; if (pty >= 5) return "빗방울"; return "정보 없음"; }
function getBgClassFromPTY(pty) { if (pty == 0) return "weather-clear"; if (pty == 1 || pty == 5) return "weather-rain"; if (pty == 3 || pty == 7) return "weather-snow"; return "weather-cloudy"; }
function createIcon(bgClass) { elements.weatherIcon.innerHTML = ''; if (bgClass === 'weather-clear') { const sun = document.createElement('div'); sun.className = 'sun'; elements.weatherIcon.appendChild(sun); } else if (bgClass === 'weather-rain') { const cloud = document.createElement('div'); cloud.className = 'cloud'; const drops = document.createElement('div'); drops.className = 'rain-drops'; for (let i = 0; i < 3; i++) { const drop = document.createElement('div'); drop.className = 'drop'; drop.style.animationDelay = `${i * 0.2}s`; drops.appendChild(drop); } cloud.appendChild(drops); elements.weatherIcon.appendChild(cloud); } else { const cloud = document.createElement('div'); cloud.className = 'cloud'; elements.weatherIcon.appendChild(cloud); } }
function showSampleData() { const sample = { temp: "21", rain: "0", pop: "10", humidity: "45", windSpeed: "2.4", windDir: 180, desc: "맑음 (샘플 데이터)", bgClass: "weather-clear" }; updateUI(sample); }
function updateClock() { const now = new Date(); const options = { year: 'numeric', month: '2-digit', day: '2-digit', hour: '2-digit', minute: '2-digit', hour12: false }; elements.currentTime.textContent = now.toLocaleString('ko-KR', options); }
elements.refreshBtn.addEventListener('click', () => { fetchWeather(); });
updateClock(); fetchWeather(); setInterval(updateClock, 60000); setInterval(fetchWeather, 600000);
